# Generated by Django 5.0.7 on 2024-09-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventphoto',
            old_name='photo',
            new_name='image',
        ),
    ]
