# Generated by Django 5.0.7 on 2024-09-07 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
