# Generated by Django 5.0.7 on 2024-09-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_photo_eventphoto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventphoto',
            old_name='image',
            new_name='photo',
        ),
    ]
