# Generated by Django 5.0.7 on 2024-09-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
