# Generated by Django 5.0.7 on 2024-09-08 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
