
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: eventhub_database
      POSTGRES_USER: alvinroot
      POSTGRES_PASSWORD: Alvin200115
    networks:
      - app-network

  web:
    build: .
    command: gunicorn event_management_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://alvinroot:Alvin200115@db:5432/eventhub_database
      - AWS_ACCESS_KEY_ID=AKIAQPHJMQZMHM5IM7J2
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=eventhub-storage
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
