name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and Push Docker Image
      run: |
        docker build -t <your-docker-image-name> .
        docker tag <your-docker-image-name> <your-dockerhub-repo>/<your-docker-image-name>:latest
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push <your-dockerhub-repo>/<your-docker-image-name>:latest

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} "
        cd /home/ubuntu/<your-project-directory> &&
        git pull origin main &&
        sudo docker-compose down &&
        sudo docker-compose up -d"
