name: Deploy Django to EC2

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: alvinksabu/django-app:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 host to known hosts
      run: ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} '
          # Update packages
          sudo apt-get update &&
          # Install Docker if not present
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io docker-compose &&
            sudo systemctl start docker &&
            sudo systemctl enable docker
          fi &&
          # Navigate to project directory
          cd /home/ubuntu/event_management_system &&
          # Clean git repository
          git clean -f &&
          # Pull latest changes
          git pull origin main &&
          # Stop running containers
          sudo docker-compose down &&
          # Pull latest images
          sudo docker-compose pull &&
          # Start containers
          sudo docker-compose up -d
        '

    - name: Verify module installations
      run: |
        ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} '
          cd /home/ubuntu/event_management_system &&
          echo "Installed Python packages:" &&
          sudo docker-compose exec -T web pip list &&
          echo "Verifying key modules:" &&
          for module in requests Django psycopg2 boto3 pillow weasyprint; do
            sudo docker-compose exec -T web python -c "import $module; print(f\"$module version: {$module.__version__}\")"
          done
        '

    - name: Run Django migrations
      run: |
        ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} '
          cd /home/ubuntu/event_management_system &&
          sudo docker-compose exec -T web python manage.py migrate
        '

    - name: Collect static files
      run: |
        ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} '
          cd /home/ubuntu/event_management_system &&
          sudo docker-compose exec -T web python manage.py collectstatic --noinput
        '

    - name: Health check
      run: |
        response=$(curl -sS -o /dev/null -w "%{http_code}" http://${{ secrets.EC2_PUBLIC_IP }})
        if [ $response = "200" ]; then
          echo "Deployment successful, site is up!"
        else
          echo "Site is not responding with 200 OK. Got response code: $response"
          exit 1
        fi

    - name: Rollback on failure
      if: failure()
      run: |
        ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} '
          cd /home/ubuntu/event_management_system &&
          sudo docker-compose down &&
          sudo docker pull alvinksabu/django-app:previous &&
          sudo docker-compose up -d
        '
