name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH for EC2 access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy repository to EC2
      run: scp -r . ubuntu@16.16.65.40:/home/ec2-user/event_management_system

    - name: SSH and run Docker Compose on EC2
      run: ssh ubuntu@16.16.65.40 "cd /home/ec2-user/event_management_system && sudo docker-compose pull && sudo docker-compose up -d"
