name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up SSH for EC2 access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 Host to Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy repository to EC2
      run: |
        rsync -av --exclude='__pycache__' --exclude='.git' . ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/event_management_system

    - name: Build and Push Docker Image
      run: |
        docker build -t event_management_system .
        docker tag event_management_system alvinksabu/event_management_system:latest
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push alvinksabu/event_management_system:latest

    - name: Deploy to EC2
      run: |
        # Save the EC2 private key to a file
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_key.pem
        chmod 400 ec2_key.pem
        
        # SSH into EC2, install Docker/Docker Compose if not already installed, pull the latest Docker image, and restart the containers
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          sudo apt-get update
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io docker-compose
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          
          # Navigate to the project directory and pull the latest changes
          cd /home/ubuntu/event_management_system || exit
          git pull origin main || exit
          
          # Stop current Docker containers, pull the latest Docker image, and restart containers
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
        EOF

    - name: Clean up SSH key
      run: rm ec2_key.pem
